### ISSUE TITLE
How to deal with package id different from class package

### ISSUE THREAD

**Issue by emartynov** [tmurakami/dexopener#10]
We started long time ago and we didn't have name for app yet. So our main package is **com.<test project name>**.

Before release, we finalised name of the app and it is stated in our **build.gradle**. However, package name in sources was not changed.

I'm trying now to use dexopener but I'm getting error from mockito that it can not mock the class.

In addition, it fails to on non final java class and non final method (I would expect it to fail on Kotlin class).

Any help with it?

**Comment by emartynov** [comment]
My apologies that it was nothing related to DexOpener.

**Comment by micHar** [comment]
Well I wouldn't say. It's a legit scenario to have different package name than app id, so it would be great to have solution for that.
