### ISSUE TITLE
Having a app crash after Studio 3.0 update

### ISSUE THREAD

**Issue by emartynov** [tmurakami/dexopener#12]
Here is the top of the exception:

``` java.io.IOError: java.io.IOException: Cannot create /data/user/0/my.package.name/code_cache/dexopener```

**Comment by tmurakami** [comment]
Could you paste your stacktrace?

**Comment by tmurakami** [comment]
Could you try `com.github.tmurakami:dexopener:81dafba081`?
If that error still occurs with `81dafba081`, please reopen this issue.
