### ISSUE TITLE
DexOpener.Builder example in README misled me

### ISSUE THREAD

**Issue by grepx** [tmurakami/dexopener#18]
Hi,
Thanks for this great library, I can finally mock my Kotlin classes! I tried to follow the instructions for DexOpener.Builder in the README and couldn't get it working until I followed the version in the sample code, which just uses `return super.newApplication(cl, className, context)`.
Maybe update it to just use that?

**Comment by tmurakami** [comment]
Sorry if I confused you.
Is there something wrong in the README?
It says to call `super.newApplication()` after calling `DexOpener.Builder#install()`...

```java
public class YourAndroidJUnitRunner extends AndroidJUnitRunner {
    @Override
    public Application newApplication(ClassLoader cl, String className, Context context)
            throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        DexOpener.builder(context)
                .buildConfig(your.app.BuildConfig.class)
                .build()
                .installTo(cl);
        // Don't call Class#getName() here.
        return super.newApplication(cl, "your.app.YourTestApplication", context);
    }
}
```

**Comment by grepx** [comment]
When I tried to hard code my test application package path it didn't work though, it couldn't find the tests. When I switched to just using `className` like in the example sample code it worked, so I'm suggesting you just change the README to:
```
public class YourAndroidJUnitRunner extends AndroidJUnitRunner {
    @Override
    public Application newApplication(ClassLoader cl, String className, Context context)
            throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        DexOpener.builder(context)
                .buildConfig(your.app.BuildConfig.class)
                .build()
                .installTo(cl);
        // Don't call Class#getName() here.
        return super.newApplication(cl, className, context);
    }
}
```

Unless there is something wrong with that? But in that case, the example sample code is wrong and needs changing.

**Comment by tmurakami** [comment]
Oh, I got it.
Sorry for my lack of explanation. 

The README indicates that you can replace the Application class for testing.

That was insufficient.
I'll update the README later.

**Comment by tmurakami** [comment]
Updated README.md.
