### ISSUE TITLE
Cannot find BuildConfig if applicationId changed for product flavor

### ISSUE THREAD

**Issue by darnmason** [tmurakami/dexopener#21]
Say my source code uses the package name `a.b.c`

Now I add a couple product flavors, `f1` and `f2`, changing my `defaultConfig` `applicationId` to `a.b`.
`f1` adds `applicationIdSuffix ".d"`.
while `f2` adds `applicationIdSuffix ".c"`, keeping the original package name.

It turns out that I can run Android tests for the variant `f2` but when using `f1` I get the `IllegalStateException` that the `BuildConfig` can't be found.

My setup is a bit more complicated than this example but this should be enough to illustrate the issue. My `BuildConfig` class will always be `a.b.c.BuildConfig` even when the application ID is `a.b.d`.

The workaround is to use the deprecated Builder to specify the BuildConfig class. I'm expecting this will be inaccessible soon so I'm highlighting that there should still be a way to specify the BuildConfig manually.

**Comment by tmurakami** [comment]
If your `defaultConfig.applicationId` is `a.b` then I think `a.b.BuildConfig` will be generated, not `a.b.c.BuildConfig`.

**Comment by darnmason** [comment]
Hey I thought that was the case at first but then both flavors would have the same exception, it must be using the suffixed application ID as one flavour works while the other doesn't.

So if there's some way to determine the actual code's package then that would do the job, otherwise providing a non deprecated method to specify the BuildConfig manually would suffice.

**Comment by tmurakami** [comment]
Oh, I see. As you say, an error will occur if the `package` attribute in the AndroidManifest.xml is different from the `defaultConfig.applicationId`. I did not consider that case.

I will provide a way to specify the BuildConfig.
Thank you.

**Comment by tmurakami** [comment]
I have just released version 2.0.0-alpha01 which fixed this issue. You can now manually specify your root package. Please see the README and the examples for more information.
