### ISSUE TITLE
Package path

### ISSUE THREAD

**Issue by realdadfish** [tmurakami/dexopener#24]
Continueing on #20 and by looking at the implementation I don't see a reason why the user of this library shouldn't be able to define one or more package paths to "open" himself. IMHO the "reasonable default" that the JUnit runner must reside _inside the root path_ and that all modules must have either the same root path or have packages underneath that sounds like an artificial limitation.

Could you elaborate a bit more what made you do this decision?

**Comment by tmurakami** [comment]
There are two reasons.

- It is very slow to open all the classes of all packages (#2). So I decided to limit classes to be opened.
- On Dalvik VM (<= API 20), classes not modified by DexOpener cannot access opened classes. So I decided to open only one package and its sub-packages in order not to confuse users of DexOpener.

**Comment by realdadfish** [comment]
OK, understood. Wouldn't it still make sense to allow the developer configure the package path by hand and only default to the runner's path if none is given?

**Comment by tmurakami** [comment]
Is there a reason why you cannot put your AndroidJUnitRunner in your root package? I don't like specifying a string literal of the root package name, so I would not change that specification unless there is a pretty good reason.

**Comment by realdadfish** [comment]
Well, imagine you put together a base test module that contains a base runner with DexOpener and a couple of other utilities (TestButler for example) and now you want to share that test module amongst different code bases. You can't do that, unless you decide to put the runner in some very "high" base package, like "com" or at least "com. company".
Furthermore, I'd like to keep my Android modules packaged according to their library ID to easily identify classes belonging to a certain module. With the runner I'd have to break with that rule, as a library "core-test" would be resembled by the library and package path "com.company.core-test", while the runner actually would have to reside in "com.company".
Last but not least it is totally unexpected that the working of the DexOpener uses the class path of the runner to get its base package. That's a bit magic that doesn't have to be IMHO. 

If you do not want to give the package by name, why not reference a specific class instead, one that is guaranteed to reside in the base package, like the auto-generated R.java?

**Comment by tmurakami** [comment]
> Well, imagine you put together a base test module that contains a base runner with DexOpener and a couple of other utilities (TestButler for example) and now you want to share that test module amongst different code bases.

I think that you can make each runner that extends the base test runner.

In the base test module:

```kotlin
package com.example.test

open class BaseAndroidJUnitRunner protected constructor() : AndroidJUnitRunner() {
    override fun newApplication(cl: ClassLoader, className: String, context: Context): Application {
        DexOpener.install(this)
        return super.newApplication(cl, className, context)
    }
}
```

In the module1:

```kotlin
package com.example.module1 // The root package of module1

class Module1AndroidJUnitRunner : BaseAndroidJUnitRunner()
```

In the module2:

```kotlin
package com.example.module2 // The root package of module2

class Module2AndroidJunitRunner : BaseAndroidJUnitRunner()
```

Then You can specify each runner in each build.gradle.

> Last but not least it is totally unexpected that the working of the DexOpener uses the class path of the runner to get its base package. That's a bit magic that doesn't have to be IMHO.

It may be a bit odd to find classes with the runner class as the root, but I think that scanning something with a particular class as the root is not that unusual. (For example, SpringBootApplication?)

> If you do not want to give the package by name, why not reference a specific class instead, one that is guaranteed to reside in the base package, like the auto-generated R.java?

Please refer to #21 for the reason why we no longer use auto-generated classes such as R.class and BuildConfig.class to detect the root package.

**Comment by realdadfish** [comment]
Well, thanks for explaining your points. I think we agree to disagree, but that is okay :)
