### ISSUE TITLE
"mockito-android" + "dexopener" - java.lang.NoClassDefFoundError: org/mockito/internal/configuration/plugins/Plugins

### ISSUE THREAD

**Issue by jaredsburrows** [tmurakami/dexopener#6]
Reposted from: https://github.com/mockito/mockito/issues/1082#issuecomment-315628196

```
java.lang.NoClassDefFoundError: org/mockito/internal/configuration/plugins/Plugins
        at org.mockito.internal.configuration.GlobalConfiguration.tryGetPluginAnnotationEngine(GlobalConfiguration.java:55)
```

Since Mockito-android is so large, I had to use LinkedIn's dexmaker.

Version of dexmaker - `0.9.2`

I was using my example project here: https://github.com/jaredsburrows/android-gif-example

**Comment by tmurakami** [comment]
I guess this is solved now, so I will close this.
If you are facing this error with the latest DexOpener, please reopen.

**Comment by jaredsburrows** [comment]
Thanks.
